config/routes.rb
Rails.application.routes.draw do
  resources :tables
  get "/products" => "products#index"
  get "/products/:id" => "products#show"
  post "/products" => "products#create"

  get "/suppliers" => "suppliers#index"
  get "/suppliers/:id" => "suppliers#show"
  post "/suppliers" => "suppliers#create"

  get "/images" => "images#index"
  get "/images/:id" => "images#show"
  post "/images" => "images#create"

  get "/orders" => "orders#index"
  post "/orders" => "orders#create"
  get "/orders/:id" => "orders#show"

  post "/signup" => "users#create"

  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  get "/carted_products" => "carted_products#index"
  post "/carted_products" => "carted_products#create"
  delete "/carted_products/:id" => "carted_products#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/carted_product.rb
class CartedProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :order, optional: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_products
  has_many :products, through: :category_products

  # def products
  #   category_products.map do |category_product|
  #     category_product.product
  #   end
  # end
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :carted_products
  has_many :products, through: :carted_products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :supplier
  has_many :images
  has_many :carted_products
  has_many :orders, through: :carted_products
  has_many :category_products
  has_many :categories, through: :category_products

  def primary_image_url
    if images.length > 0
      images[0].url
    else
      "https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg"
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
end

app/models/table.rb
class Table < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true

  has_many :orders
  has_many :carted_products
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all

    render :index
  end

  def show
    @image = Image.find(params[:id])

    render :show
  end

  def create
    @image = Image.create(
      url: params[:url],
      product_id: params[:product_id]
    )

    if @image.valid?
      render :show
    else
      render json: { errors: @image.errors.full_messages }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user

  def index
    # SLOW BUT EASIER TO READ VERSION:
    # @orders = current_user.orders
    # Rails will automatically load carted_products and products when accessed in the view
    # But it makes separate database queries for each order's items (N+1 query problem)
    
    # FAST BUT MORE COMPLEX VERSION:
    # .includes(carted_products: :product) tells Rails to load the orders AND their associated carted_products AND each carted_product's product in one efficient database query
    # Without this, Rails would make separate queries for each order's items (N+1 query problem)
    # With this, Rails loads everything at once, making it much faster
    @orders = current_user.orders.includes(carted_products: :product)

    render :index
  end

  def create
    # grab the carted products for this user where the status is carted
    carted_products = current_user.carted_products.where(status: "carted")

    # calculate the subtotal, tax, and total, based on the quantities from the carted product and the price of each product
    calculated_subtotal = 0

    carted_products.each do |carted_product|
      calculated_subtotal += carted_product.quantity * carted_product.product.price
    end

    calculated_tax = calculated_subtotal * 0.08
    calculated_total = calculated_tax + calculated_subtotal

    # create the order with the calculations and the user's id
    @order = Order.create(
      user_id: current_user.id,
      subtotal: calculated_subtotal,
      tax: calculated_tax,
      total: calculated_total
    )

    # update all of the user's carted products with the status of carted to be "purchased"
    carted_products.update_all(status: "purchased", order_id: @order.id)

    # render the order
    render json: @order
  end

  def show
    # @order = Order.find(params[:id])
    # @order = Order.find_by(id: params[:id])
    @order = current_user.orders.find_by(id: params[:id])
    # can use find, however, it throws a lot harsher errors
    # @order = current_user.orders.find(params[:id])

    if @order
      render json: @order
    else
      render json: { message: "Not your order..." }
    end
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: %i[ show edit update destroy ]

  # GET /tables or /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1 or /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
  end

  # POST /tables or /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: "Table was successfully created." }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1 or /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: "Table was successfully updated." }
        format.json { render :show, status: :ok, location: @table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1 or /tables/1.json
  def destroy
    @table.destroy!

    respond_to do |format|
      format.html { redirect_to tables_path, status: :see_other, notice: "Table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def table_params
      params.expect(table: [ :height, :width, :description ])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
      password_confirmation: params[:password_confirmation]
    )
    if user.save
      render json: { message: "User created successfully" }, status: :created
    else
      render json: { errors: user.errors.full_messages }, status: :bad_request
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tables/_form.html.erb
<%= form_with(model: table) do |form| %>
  <% if table.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
        <% table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.number_field :height %>
  </div>

  <div>
    <%= form.label :width, style: "display: block" %>
    <%= form.number_field :width %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/_table.html.erb
<div id="<%= dom_id table %>">
  <p>
    <strong>Height:</strong>
    <%= table.height %>
  </p>

  <p>
    <strong>Width:</strong>
    <%= table.width %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= table.description %>
  </p>

</div>

app/views/tables/edit.html.erb
<% content_for :title, "Editing table" %>

<h1>Editing table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%= link_to "Show this table", @table %> |
  <%= link_to "Back to tables", tables_path %>
</div>

app/views/tables/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Tables" %>

<h1>Tables</h1>

<div id="tables">
  <% @tables.each do |table| %>
    <%= render table %>
    <p>
      <%= link_to "Show this table", table %>
    </p>
  <% end %>
</div>

<%= link_to "New table", new_table_path %>

app/views/tables/new.html.erb
<% content_for :title, "New table" %>

<h1>New table</h1>

<%= render "form", table: @table %>

<br>

<div>
  <%= link_to "Back to tables", tables_path %>
</div>

app/views/tables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @table %>

<div>
  <%= link_to "Edit this table", edit_table_path(@table) %> |
  <%= link_to "Back to tables", tables_path %>

  <%= button_to "Destroy this table", @table, method: :delete %>
</div>